#!/bin/bash
dir="$(pwd)"
find "$dir" -type d -name '.git' | grep -v '/vendor/' | while read g; do
    echo -e '\n\n\n'
    cd "$g/.."
    pwd
    git "$@"
    cd "$dir"
    echo -e '\n\n\n\n------------------'
done
