#!/bin/bash

find . -type d -name '.git' | grep -v '/vendor/' | while read g; do
    (
        cd "$g/.."

        if [ -n "$(git diff)" -o -n "$(git ls-files --others --exclude-standard)" ]; then
            if [ "$1" == '-v' ]; then
                echo -e '\n\n\n'
                pwd
                git diff
                echo -e '\n\n\n\n------------------'
            else
                pwd
            fi
        fi
    )
done
